//부서명, 직원이름
    SELECT D.DEPARTMENT_NAME, E.FIRST_NAME || ' ' || E.LAST_NAME
    FROM DEPARTMENTS D, EMPLOYEES E
    WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID;
    
    CREATE OR REPLACE PROCEDURE  Get_DNAME_ENAME( 
    IN_EMPID   IN   NUMBER,
    O_DNAME    OUT  VARCHAR2,
    O_ENAME    OUT  VARCHAR2
) 
AS  
    BEGIN
      SELECT   D.DEPARTMENT_NAME,  E.FIRST_NAME || ' ' || E.LAST_NAME
       INTO    O_DNAME          , O_ENAME
       FROM    DEPARTMENTS  D, EMPLOYEES E
       WHERE   D.DEPARTMENT_ID  =  E.DEPARTMENT_ID
        AND    E.EMPLOYEE_ID    =  IN_EMPID ;
  END;
/
var    O_DNAME VARCHAR2;
var    O_ENAME VARCHAR2;
exec Get_DNAME_ENAME(100, :O_DNAME, :O_ENAME);
PRINT O_DNAME;
PRINT O_ENAME;